In [3]:
import pandas as pd
df = pd.read_csv("data.csv")

In [4]:
df.head()

,employee_id,performance,years_of_exp,projects_completed,bonus
0,EMP_001,7,1,10,130
1,EMP_002,4,8,7,130
2,EMP_003,8,4,9,158
3,EMP_004,5,4,17,138
4,EMP_005,7,5,11,156


In [5]:
df.shape

(1000, 5)

In [36]:
from sklearn.model_selection import train_test_split
X = df[['performance', 'years_of_exp', 'projects_completed']].values
y = df[['bonus']].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [37]:
import sys
!{sys.executable} -m pip install scikit-learn

In [38]:
X_train.shape

(800, 3)

In [39]:
y_test.shape

(200, 1)

In [40]:
import torch
import torch.nn as nn
import torch.optim as optim 


In [41]:
X_train_tensor = torch.tensor(X_train,dtype = torch.float32)
y_train_tensor = torch.tensor(y_train,dtype = torch.float32)
X_test_tensor = torch.tensor(X_test,dtype = torch.float32)
y_test_tensor = torch.tensor(y_test,dtype = torch.float32)

In [42]:
class  BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(3,1) # 3 input features and 1 output layer  
        )
    def forward(self,X):
        return self.network(X)

In [47]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr = 0.005)

In [48]:
epochs = 5000
for epoch in range(epochs):
     # Forward pass
     predictions = model(X_train_tensor)
     loss = criterion(predictions,y_train_tensor)

     # backward 
     optimizer.zero_grad()
     loss.backward()

    
     # update weights 
     optimizer.step()

     if ( epoch + 1) % 100 ==  0 :
         print(f" Epoch [{epoch + 1}/{epochs}], Loss : {loss.item():.2f}")

 Epoch [100/5000], Loss : 26.77
 Epoch [200/5000], Loss : 22.33
 Epoch [300/5000], Loss : 18.62
 Epoch [400/5000], Loss : 15.53
 Epoch [500/5000], Loss : 12.95
 Epoch [600/5000], Loss : 10.80
 Epoch [700/5000], Loss : 9.01
 Epoch [800/5000], Loss : 7.51
 Epoch [900/5000], Loss : 6.27
 Epoch [1000/5000], Loss : 5.22
 Epoch [1100/5000], Loss : 4.36
 Epoch [1200/5000], Loss : 3.63
 Epoch [1300/5000], Loss : 3.03
 Epoch [1400/5000], Loss : 2.53
 Epoch [1500/5000], Loss : 2.11
 Epoch [1600/5000], Loss : 1.76
 Epoch [1700/5000], Loss : 1.47
 Epoch [1800/5000], Loss : 1.22
 Epoch [1900/5000], Loss : 1.02
 Epoch [2000/5000], Loss : 0.85
 Epoch [2100/5000], Loss : 0.71
 Epoch [2200/5000], Loss : 0.59
 Epoch [2300/5000], Loss : 0.49
 Epoch [2400/5000], Loss : 0.41
 Epoch [2500/5000], Loss : 0.34
 Epoch [2600/5000], Loss : 0.29
 Epoch [2700/5000], Loss : 0.24
 Epoch [2800/5000], Loss : 0.20
 Epoch [2900/5000], Loss : 0.17
 Epoch [3000/5000], Loss : 0.14
 Epoch [3100/5000], Loss : 0.12
 Epoch [320

In [51]:
model.eval()
with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)

print(f" Test Loss :{ test_loss.item():.2f}")

 Test Loss :0.00


In [52]:
test_predictions[:3]

tensor([[196.0723],
        [174.0259],
        [113.9617]])

In [54]:
y_test_tensor[:3]


tensor([[196.],
        [174.],
        [114.]])

In [56]:
# w1 = 12, w2 = 6 , w3 = 2 , bias = 20

for name , value in model.named_parameters():
    print(f"Name : {name}, Value : {value}")

Name : network.0.weight, Value : Parameter containing:
tensor([[12.0118,  6.0116,  2.0057]], requires_grad=True)
Name : network.0.bias, Value : Parameter containing:
tensor([19.7999], requires_grad=True)
