In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.tensor(9)

tensor(9)

In [5]:
revenue = torch.tensor([100,200,300])

In [6]:
revenue

tensor([100, 200, 300])

In [7]:
revenue[:2]

tensor([100, 200])

In [8]:
q1 = torch.tensor([[200,220,250],[150,180,210],[300,330,360]])
q2 = torch.tensor([[209,231,259],[155,192,222],[310,340,375]])

In [9]:
q1,q2

(tensor([[200, 220, 250],
         [150, 180, 210],
         [300, 330, 360]]),
 tensor([[209, 231, 259],
         [155, 192, 222],
         [310, 340, 375]]))

In [10]:
q1+q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [11]:
q2-q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [12]:
return_rate = 0.1
return_rate*q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [13]:
if torch.cuda.is_available() :
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

In [14]:
cust_data = torch.rand(1_000_000,3,device=device)

In [15]:
cust_data

tensor([[0.6310, 0.7690, 0.2397],
        [0.0304, 0.2868, 0.9732],
        [0.4663, 0.3731, 0.2916],
        ...,
        [0.3099, 0.7694, 0.9416],
        [0.2619, 0.4923, 0.7266],
        [0.2135, 0.2840, 0.7389]], device='cuda:0')

In [16]:
cust_data.shape

torch.Size([1000000, 3])

In [17]:
cust_data[:3]

tensor([[0.6310, 0.7690, 0.2397],
        [0.0304, 0.2868, 0.9732],
        [0.4663, 0.3731, 0.2916]], device='cuda:0')

In [18]:
cust_data[:,1]

tensor([0.7690, 0.2868, 0.3731,  ..., 0.7694, 0.4923, 0.2840], device='cuda:0')

In [19]:
cust_data[cust_data[:,1]>0.55]

tensor([[0.6310, 0.7690, 0.2397],
        [0.5774, 0.6704, 0.3080],
        [0.6747, 0.9555, 0.5851],
        ...,
        [0.8708, 0.7369, 0.9233],
        [0.6106, 0.8611, 0.0810],
        [0.3099, 0.7694, 0.9416]], device='cuda:0')

In [20]:
units = torch.tensor([[200,220,250],
                      [150,180,210],
                      [300,330,360]])

In [32]:
units.shape

torch.Size([3, 3])

In [22]:
units.dtype

torch.int64

In [23]:
units.device

device(type='cpu')

In [24]:
units.view(-1)

tensor([200, 220, 250, 150, 180, 210, 300, 330, 360])

In [25]:
units.view(9,1)

tensor([[200],
        [220],
        [250],
        [150],
        [180],
        [210],
        [300],
        [330],
        [360]])

In [26]:
units.view(9)

tensor([200, 220, 250, 150, 180, 210, 300, 330, 360])

In [27]:
units[1,1] = 71

In [28]:
units

tensor([[200, 220, 250],
        [150,  71, 210],
        [300, 330, 360]])

In [29]:
torch.rand(3,4)

tensor([[0.7432, 0.4636, 0.6683, 0.0315],
        [0.5096, 0.9627, 0.2003, 0.3814],
        [0.7183, 0.1357, 0.8931, 0.4765]])

In [30]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
torch.cuda.is_available()

True